### PR TITLE
Improved design

### PR DESCRIPTION
**Pull request by Andy-404**
### Demo Video
https://user-images.githubusercontent.com/68277858/122682594-0b908200-d218-11eb-9dbb-b397c74e4f4e.mp4

### CODE REVIEW

**Comment by Akash-Ramjyothi** [comment]
@Andy-404 I really do like the new design. But I have a few comments. The heading Code in ... 's style does not fit with the Background color.

**Comment by Andy-404** [comment]
Screenshot_2
Which one do you prefer @Akash-Ramjyothi ?
Or if you have something else in mind then please tell.

**Comment by Andy-404** [comment]
Screenshot_7
Screenshot_8
How about these @Akash-Ramjyothi

**Comment by Akash-Ramjyothi** [comment]
@Andy-404 can you please implement the first Pallete design? I feel it has a better design. And I am sorry that I do not like the change in Title. I like it to be **"Coder HCJ"** only.

**Comment by Andy-404** [comment]
image
Is this header fine @Akash-Ramjyothi ?

**Comment by Akash-Ramjyothi** [comment]
@Andy-404 unfortunately this header is not good. I don't think it is good to have the font in `Times New Roman`, please try in `Roboto` and I would like to have the style to be in `bold`. And I think you also need to change the color of the header because of the Pallete I suggested before.

**Comment by Andy-404** [comment]
image
Will this work @Akash-Ramjyothi ?

**Comment by Akash-Ramjyothi** [comment]
@Andy-404 it is good that I can see the drastic improvement. Can you please Increase the heading size of the title "Coder HCJ"? Please make the heading in Bold style. There should be a space between such as: "Coder <Space> HCJ". Also I do not think having the heading to be Dark blue font color in a light blue background. Unfortunately, I could not think of another color for the heading to be suitable with the light blue background. Please suggest me any other color for the heading, if not possible, then the dark blue would work fine.

**Comment by Andy-404** [comment]
image

Would this work @Akash-Ramjyothi ?
If this is fine then I will commit the change

**Comment by Akash-Ramjyothi** [comment]
@Andy-404 Can you please further increase the font size and make it Bold?

**Comment by Andy-404** [comment]
image

The font-weight is max (i.e. 900) so it can't be increased any further @Akash-Ramjyothi

**Comment by Akash-Ramjyothi** [comment]
Ok, understood. Please make the text in Bold and put space between Coder and HCJ.

**Comment by Andy-404** [comment]
image

It won't get bolder than this using font-weight, can you recommend any other way to do it or is it fine @Akash-Ramjyothi ?

**Comment by Akash-Ramjyothi** [comment]
Ok, this is fine. Please commit if you have any other changes to make it adhere with the above Image. Also please post here a Demo video. Use this as reference and perform the functionalities as shown: https://github.com/Akash-Ramjyothi/Coder-HCJ#-sample-demo. If the demo is fine, then I will merge it.

**Comment by Andy-404** [comment]
https://user-images.githubusercontent.com/68277858/124969035-da031d80-e043-11eb-8647-120ec806a90f.mp4

Anything else you would suggest adding @Akash-Ramjyothi ?

**Comment by Akash-Ramjyothi** [comment]
@Andy-404 You have shown your utmost hardwork, dedication and most importantly your consistency in this Feature. You have done a really good job. Thank you so much for your contributions. 

I am Merging this PR as it drastically improves the existing interface.

**Comment by Andy-404** [comment]
Glad you liked it!

**Pull request merged**
